name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install qt5-default

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install g++

      - name: Compile and Run tests.cpp
        run: |
          qmake telbook.pro
          make
          ./tests
