name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt and g++
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev g++
          sudo apt-get install qt5-qmake

      - name: Compile and Run tests.cpp
        run: |
          qmake tests.pro
          make
          ./tests
